### ISSUE TITLE
example data sctruture missing in generated html

### ISSUE THREAD

**Issue by gureedo** [danielgtaylor/aglio#176] opened 2015-09-29 06:21 UTC
example.apib has section with data structure
```markdown
# Data Structures

## NoteData
+ id: 1 (required, number) - Unique identifier
+ title: Grocery list (required) - Single line description
+ body: Buy milk - Full description of the note which supports Markdown.

## NoteList (array[NoteData])
```
And this text is missing in generated HTML file.

**Comment by danielgtaylor** [comment] 2015-10-02 08:43
@gureedo this is a duplicate of #103. I am working on displaying data structures in a sane way, but it requires some changes to Aglio's dependencies. It's one of my top priorities at the moment.

**Closed by danielgtaylor** 2015-10-02 08:43 UTC
Labels: duplicate
