### ISSUE TITLE
Fails to install due to generic Linux error

### ISSUE THREAD

**Issue by dmtroll** [danielgtaylor/aglio#180] opened 2015-10-02 16:29 UTC
Pretty much what the title says. Below is my npm-debug.log, shortened for easier reading.

```
29144 info preinstall nan@1.8.4
29145 verbose readDependencies loading dependencies from /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter/node_modules/protagonist/node_modules/nan/package.json
29146 verbose readDependencies loading dependencies from /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter/node_modules/protagonist/node_modules/nan/package.json
29147 silly install resolved []
29148 verbose about to build /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter/node_modules/protagonist/node_modules/nan
29149 info build /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter/node_modules/protagonist/node_modules/nan
29150 info linkStuff nan@1.8.4
29151 silly linkStuff nan@1.8.4 has /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter/node_modules/protagonist/node_modules as its parent node_modules
29152 silly linkStuff nan@1.8.4 is part of a global install
29153 silly linkStuff nan@1.8.4 is installed into a global node_modules
29154 verbose linkBins nan@1.8.4
29155 verbose linkMans nan@1.8.4
29156 verbose rebuildBundles nan@1.8.4
29157 info install nan@1.8.4
29158 info postinstall nan@1.8.4
29159 verbose unlock done using /root/.npm/_locks/nan-72e2fff637a9f4d8.lock for /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter/node_modules/protagonist/node_modules/nan
29160 verbose about to build /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter/node_modules/protagonist
29161 info build /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter/node_modules/protagonist
29162 info linkStuff protagonist@0.20.1
29163 silly linkStuff protagonist@0.20.1 has /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter/node_modules as its parent node_modules
29164 silly linkStuff protagonist@0.20.1 is part of a global install
29165 silly linkStuff protagonist@0.20.1 is installed into a global node_modules
29166 verbose linkBins protagonist@0.20.1
29167 verbose linkMans protagonist@0.20.1
29168 verbose rebuildBundles protagonist@0.20.1
29169 verbose rebuildBundles [ 'nan' ]
29170 info install protagonist@0.20.1
29171 verbose unsafe-perm in lifecycle false
29172 info protagonist@0.20.1 Failed to exec install script
29173 verbose unlock done using /root/.npm/_locks/protagonist-937b27105415bed5.lock for /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter/node_modules/protagonist
29174 verbose about to build /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter
29175 verbose unlock done using /root/.npm/_locks/drafter-34cea0abfb515abd.lock for /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter
29176 verbose about to build /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio
29177 verbose unlock done using /root/.npm/_locks/aglio-fabe00b3c5e4dcba.lock for /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio
29178 verbose stack Error: aglio-theme-olio@1.2.1 postinstall: `node scripts/setup-cache.js`
29178 verbose stack spawn ENOENT
29178 verbose stack     at ChildProcess.<anonymous> (/home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:17:16)
29178 verbose stack     at emitTwo (events.js:87:13)
29178 verbose stack     at ChildProcess.emit (events.js:172:7)
29178 verbose stack     at maybeClose (internal/child_process.js:817:16)
29178 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
29179 verbose pkgid aglio-theme-olio@1.2.1
29180 verbose cwd /home/kyle/Downloads/node-v4.1.1-linux-x64
29181 error Linux 3.13.0-37-generic
29182 error argv "/home/kyle/Downloads/node-v4.1.1-linux-x64/bin/node" "/home/kyle/Downloads/node-v4.1.1-linux-x64/bin/npm" "install" "-g" "aglio" "--python=python2.7"
29183 error node v4.1.1
29184 error npm  v2.14.4
29185 error file sh
29186 error code ELIFECYCLE
29187 error errno ENOENT
29188 error syscall spawn
29189 error aglio-theme-olio@1.2.1 postinstall: `node scripts/setup-cache.js`
29189 error spawn ENOENT
29190 error Failed at the aglio-theme-olio@1.2.1 postinstall script 'node scripts/setup-cache.js'.
29190 error This is most likely a problem with the aglio-theme-olio package,
29190 error not with npm itself.
29190 error Tell the author that this fails on your system:
29190 error     node scripts/setup-cache.js
29190 error You can get their info via:
29190 error     npm owner ls aglio-theme-olio
29190 error There is likely additional logging output above.
29191 verbose exit [ 1, true ]
29192 verbose unbuild lib/node_modules/aglio/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
29193 info preuninstall utf-8-validate@1.2.1
29194 info uninstall utf-8-validate@1.2.1
29195 verbose unbuild rmStuff utf-8-validate@1.2.1 from /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules
29196 verbose unbuild rmStuff in /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules
29197 info postuninstall utf-8-validate@1.2.1
29198 silly gentlyRm /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate is being purged from base /home/kyle/Downloads/node-v4.1.1-linux-x64
29199 verbose gentlyRm don't care about contents; nuking /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
29200 silly vacuum-fs purging /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
29201 silly vacuum-fs quitting because other entries in /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules
29202 verbose unbuild lib/node_modules/aglio/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
29203 info preuninstall bufferutil@1.2.1
29204 info uninstall bufferutil@1.2.1
29205 verbose unbuild rmStuff bufferutil@1.2.1 from /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules
29206 verbose unbuild rmStuff in /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules
29207 info postuninstall bufferutil@1.2.1
29208 silly gentlyRm /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil is being purged from base /home/kyle/Downloads/node-v4.1.1-linux-x64
29209 verbose gentlyRm don't care about contents; nuking /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
29210 silly vacuum-fs purging /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
29211 silly vacuum-fs quitting because other entries in /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules
29212 verbose unbuild lib/node_modules/aglio/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
29213 info preuninstall utf-8-validate@1.2.1
29214 info uninstall utf-8-validate@1.2.1
29215 verbose unbuild rmStuff utf-8-validate@1.2.1 from /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules
29216 verbose unbuild rmStuff in /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules
29217 info postuninstall utf-8-validate@1.2.1
29218 silly gentlyRm /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate is being purged from base /home/kyle/Downloads/node-v4.1.1-linux-x64
29219 verbose gentlyRm don't care about contents; nuking /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
29220 silly vacuum-fs purging /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
29221 silly vacuum-fs quitting because other entries in /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules
29222 verbose unbuild lib/node_modules/aglio/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
29223 info preuninstall bufferutil@1.2.1
29224 info uninstall bufferutil@1.2.1
29225 verbose unbuild rmStuff bufferutil@1.2.1 from /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules
29226 verbose unbuild rmStuff in /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules
29227 info postuninstall bufferutil@1.2.1
29228 silly gentlyRm /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil is being purged from base /home/kyle/Downloads/node-v4.1.1-linux-x64
29229 verbose gentlyRm don't care about contents; nuking /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
29230 silly vacuum-fs purging /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
29231 silly vacuum-fs quitting because other entries in /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules
29232 verbose unbuild lib/node_modules/aglio/node_modules/aglio-theme-olio
29233 info preuninstall aglio-theme-olio@1.2.1
29234 info uninstall aglio-theme-olio@1.2.1
29235 verbose unbuild rmStuff aglio-theme-olio@1.2.1 from /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules
29236 verbose unbuild rmStuff in /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules
29237 info postuninstall aglio-theme-olio@1.2.1
29238 silly gentlyRm /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/aglio-theme-olio is being purged from base /home/kyle/Downloads/node-v4.1.1-linux-x64
29239 verbose gentlyRm don't care about contents; nuking /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/aglio-theme-olio
29240 silly vacuum-fs purging /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/aglio-theme-olio
29241 silly vacuum-fs quitting because other entries in /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules
29242 verbose unbuild lib/node_modules/aglio/node_modules/drafter/node_modules/protagonist
29243 info preuninstall protagonist@0.20.1
29244 info uninstall protagonist@0.20.1
29245 verbose unbuild rmStuff protagonist@0.20.1 from /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules
29246 verbose unbuild rmStuff in /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter/node_modules
29247 info postuninstall protagonist@0.20.1
29248 silly gentlyRm /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter/node_modules/protagonist is being purged from base /home/kyle/Downloads/node-v4.1.1-linux-x64
29249 verbose gentlyRm don't care about contents; nuking /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter/node_modules/protagonist
29250 silly vacuum-fs purging /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter/node_modules/protagonist
29251 silly vacuum-fs quitting because other entries in /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter/node_modules
29252 verbose unbuild lib/node_modules/aglio/node_modules/drafter
29253 info preuninstall drafter@0.2.8
29254 info uninstall drafter@0.2.8
29255 verbose unbuild rmStuff drafter@0.2.8 from /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules
29256 verbose unbuild rmStuff in /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules
29257 silly gentlyRm /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/.bin/drafter is being gently removed
29258 silly gentlyRm verifying /home/kyle/Downloads/node-v4.1.1-linux-x64 is an npm working directory
29259 silly gentlyRm containing path /home/kyle/Downloads/node-v4.1.1-linux-x64 is under npm's control, in /home/kyle/Downloads/node-v4.1.1-linux-x64
29260 silly gentlyRm deletion target /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/.bin/drafter is under /home/kyle/Downloads/node-v4.1.1-linux-x64
29261 verbose gentlyRm vacuuming from /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/.bin/drafter up to /home/kyle/Downloads/node-v4.1.1-linux-x64
29262 info postuninstall drafter@0.2.8
29263 silly gentlyRm /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter is being purged from base /home/kyle/Downloads/node-v4.1.1-linux-x64
29264 verbose gentlyRm don't care about contents; nuking /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter
29265 silly vacuum-fs purging /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules/drafter
29266 silly vacuum-fs quitting because other entries in /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio/node_modules
29267 verbose unbuild lib/node_modules/aglio
29268 info preuninstall aglio@2.1.1
29269 info uninstall aglio@2.1.1
29270 verbose unbuild rmStuff aglio@2.1.1 from /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules
29271 silly gentlyRm /home/kyle/Downloads/node-v4.1.1-linux-x64/bin/aglio is being gently removed
29272 silly gentlyRm verifying /home/kyle/Downloads/node-v4.1.1-linux-x64 is an npm working directory
29273 silly gentlyRm containing path /home/kyle/Downloads/node-v4.1.1-linux-x64 is under npm's control, in /home/kyle/Downloads/node-v4.1.1-linux-x64
29274 silly gentlyRm deletion target /home/kyle/Downloads/node-v4.1.1-linux-x64/bin/aglio is under /home/kyle/Downloads/node-v4.1.1-linux-x64
29275 verbose gentlyRm vacuuming from /home/kyle/Downloads/node-v4.1.1-linux-x64/bin/aglio up to /home/kyle/Downloads/node-v4.1.1-linux-x64
29276 info postuninstall aglio@2.1.1
29277 silly gentlyRm /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio is being purged from base /home/kyle/Downloads/node-v4.1.1-linux-x64
29278 verbose gentlyRm don't care about contents; nuking /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio
29279 silly vacuum-fs purging /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules/aglio
29280 silly vacuum-fs quitting because other entries in /home/kyle/Downloads/node-v4.1.1-linux-x64/lib/node_modules
```

**Comment by danielgtaylor** [comment] 2015-10-05 09:07
@dmtroll it looks like you are using Node 4.1.1. One of our dependencies ([Protagonist](https://github.com/apiaryio/protagonist)) does not support Node 4.x yet. There is an [in-progress pull request](https://github.com/apiaryio/protagonist/pull/90) to get it working so it should get released soon.

Until then you can downgrade to an earlier version of Node.js.

**Comment by danielgtaylor** [comment] 2015-10-05 09:08
Btw, I believe #175 is a duplicate of this issue.

**Comment by danielgtaylor** [comment] 2015-10-26 20:13
@dmtroll Node.js 4.x should now work with the latest release!

**Closed by danielgtaylor** 2015-10-26 20:13 UTC
Labels: duplicate, pending upstream release
