### ISSUE TITLE
Add command line flag to render "Data Structures"

### ISSUE THREAD

**Issue by OgreSwamp** [danielgtaylor/aglio#171] opened 2015-09-17 15:42 UTC
Data Structures are great for describing data types in JSON bodies / Data Schema sections.
But they are also great as data objects description. It will be great if we can render the whole section "Data types" with object structure and description as tables.

**Comment by danielgtaylor** [comment] 2015-09-18 11:32
@OgreSwamp this is a duplicate of #103 - please leave any new comments there!

I'm working on making this a reality, but it required a lot of (currently ongoing) work in upstream projects first. Don't worry, awesome stuff is on the horizon!

**Closed** 2015-09-18 11:32 UTC
Labels: duplicate
