### ISSUE TITLE
Rendering issues for Aglio >= 1.16.2

### ISSUE THREAD

**Issue by NobodysNightmare** [danielgtaylor/aglio#78] opened 2015-01-14 11:20 UTC
Hello,

today I installed aglio on my new machine and it struggled to render a document that worked fine for an existing install of aglio on another machine.

The document in question is: [The OpenProject APIv3 spec](https://github.com/opf/openproject/blob/a3839a19c2e66b2ae879b2f3374003f805660a0a/doc/apiv3-documentation.apib)

When running as a server, I get a short console output and then aglio *immediately terminates*:
````bash
$ aglio -i .\doc\apiv3-documentation.apib --server
Server started on http://127.0.0.1:3000/
Rendering .\doc\apiv3-documentation.apib
$
````

Trying to output into a file gives me no output at all and there is also no file created:

````bash
$ aglio -i .\doc\apiv3-documentation.apib -o foo.html
$
````

However, a minimalistic test file works:

````markdown
FORMAT: 1A

# OpenProject API v3

# Group General

Test
````

I am running aglio on windows if that matters.

After checking `npm view aglio versions` I tested since when the problem occurs.

Version **1.12.0** through **1.16.1** work fine, starting with **1.16.2** the described behaviour occurs.

I can provide more details if you tell me what you might need.

Best regards
Jan Sandbrink

**Comment by danielgtaylor** [comment] 2015-01-15 18:31
@NobodysNightmare the given file appears to work for me. I'm not using Windows but I don't think that should matter. Is it possible you are running out of memory on your machine? What if you only render say half the document?

![screen shot 2015-01-15 at 10 28 46 am](https://cloud.githubusercontent.com/assets/106826/5763710/9a88af18-9ca1-11e4-80e8-05db6278583c.png)

**Comment by danielgtaylor** [comment] 2015-01-19 17:47
@NobodysNightmare any update on this?

**Comment by NobodysNightmare** [comment] 2015-01-19 17:52
Sorry, had no time to test your proposal. Don't think it is a memory issue... I hope...
 8 GiB of RAM should be enough for everyone :-)

I will test to make the document smaller tomorrow. However, this would not be a viable workaround. The document will tend to become even bigger.

Best regards
Jan

Am 19. Januar 2015 18:47:12 MEZ, schrieb "Daniel G. Taylor" <notifications@github.com>:
>@NobodysNightmare any update on this?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/danielgtaylor/aglio/issues/78#issuecomment-70533417

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by NobodysNightmare** [comment] 2015-01-20 09:33
First of all I have to correct my specs: My machine at work has 12 GiB of physical memory

I did some further tests with aglio 1.17.1 using the following commandline:

````
aglio -i .\doc\apiv3-documentation.apib --server
````

Using my resource monitor and running aglio multiple times I could not see anything pointing to excessive memory usage.
Computers are fast and I did not professionally profile the application, I just had the task manager open and checked for total memory comsumption and processes with most comsumption. Running aglio did not ring any alarms there (I ran it like 10 times in case the spike was just to short to notice)...

On trying to reduce the size of the document things start to get weird. I cut the document by multiple sections.
As soon as I only leave the preamble and the attachments group ([gist here](https://gist.github.com/NobodysNightmare/5095a25d6f1c9662db46)) the results become **unstable**: Sometimes it renders, sometimes it does not... I would say it succeeds like one in four tries.

By cutting the attachments section (leaving only the first 397 lines), I could not cause any failure in 10 tries.

**Conclusion**: Things are weird....

I also tried [comparing version 1.16.1 to 1.16.2](https://github.com/danielgtaylor/aglio/compare/v1.16.1...v1.16.2), because the latter introduced my problems. My analysis here is vague at best because I did never work with any of the tools you are using, but it seems that the only considerable change is that you updated your dependencies (assuming that the examples are not relevant and that your changes to `templates/_bootstrap-mixins.jade` did not cause that behaviour).
However, due to my lack of knowledge I really don't know which dependency would be able to cause that behaviour.

I know it sucks to get bug reports that you can't reproduce yourself :/ Anything more I could do?

**Comment by NobodysNightmare** [comment] 2015-01-20 10:13
Something about OS'es and specs, all for Aglio 1.17.1

## Failing machines

my machine: Windows 8.1 (12 GiB RAM)
my old machine: Windows 7 (8 GiB RAM)
colleague #1 machine: Windows 8.1 (16 GiB RAM)

## Succeeding machines

colleague #2 machine: Mac OS X (?? GiB RAM)
CI machine: Ubuntu 12.04.5 LTS (12 GiB; virtualized)

**Comment by theOne3mind** [comment] 2015-01-22 09:20
I do have the same behavior (very unstable rendering, works only <20% of attempts.
I'm running the same machine as before the update (Windows 7 with 16GB RAM).
I tried also splitting and using the include-mechanism, didn't work either.

**Comment by danielgtaylor** [comment] 2015-01-22 17:10
This is really interesting. Could you try to install these branches and test if they exhibit the same behavior? One is switching back to `marked` for Markdown rendering, the other is moving to `markdown-it` instead of `remarkable`.

```bash
$ mkdir tmp
$ cd tmp

# This one should just work, it was what we used before
$ npm install git://github.com/danielgtaylor/aglio#marked
$ node_modules/aglio/bin/aglio.js -i yourfile.apib -o output.html

# This one may work, please let me know if it does
$ rm -rf node_modules
$ npm install git://github.com/danielgtaylor/aglio#markdown-it
$ node_modules/aglio/bin/aglio.js -i yourfile.apib -o output.html
```

I wish I had a good way to automate the testing on Windows. If you have any ideas, please let me know.

**Comment by theOne3mind** [comment] 2015-01-23 09:37
@danielgtaylor 
Tried both branches. Same result unfortuantely.
Do both of them support the include-syntax?
Anything else I could try?

**Comment by NobodysNightmare** [comment] 2015-01-23 10:15
Same result for me too, my test command line looks like:

````
node.exe node_modules/aglio/bin/aglio.js -i doc\apiv3-documentation.apib --server
````

Notice that the errors already started **in version 1.16.2**, looking at the diff between [1.16.1 and 1.16.2](https://github.com/danielgtaylor/aglio/compare/v1.16.1...v1.16.2) I see that marked was not replaced there (merely its version number was increased).

If I had to guess (remember me knowing near nothing ^^) I would say it could be protagonist, because its version jump looks like the biggest.

I'll try to figure out how to build aglio myself and vary the dependencies... (if I can acomplish that)

**Comment by danielgtaylor** [comment] 2015-01-23 17:39
Very strange. It does sound like the culprit could be protagonist. Let's try this, then. Clone your fork to your machine and adjust the dependencies until it works:

```bash
npm install -g grunt-cli
mkdir test
cd test
git clone https://github.com/NobodysNightmare/aglio.git
cd algio
# Modify package.json, e.g. to depend on "protagonist": "0.12.1"
npm install
node bin/aglio.js -i yourfile.apib -o output.html
# If this works, increase the minor version number
```

If you can figure out the version of protagonist that's causing the problem then I can push the issue upstream. Also, you could try installing the latest protagonist (`npm install protagonist`) and see if that fixes the issue. If so, we could just do another patch release with the dependencies bumped.

**Comment by theOne3mind** [comment] 2015-01-26 14:02
Hey guys,
kind of good news here. I was able to pinpoint the problem to the *protagonist* reference.

**What I did**
Basically I tried various combinations before establishing a reproducible behaviour.
Using latest aglio (`npm install aglio`), I manually removed the protagonist directory from node_modules, and tried different versions (`npm install protagonist@0.16.0`).

Latest Aglio with Protagonist 0.16.0 -> transformation of large file works
Latest Aglio with Protagonist 0.17.0 or 0.17.1 -> transformation broken

Other references remained unchanged.

**Comment by danielgtaylor** [comment] 2015-01-26 17:27
@theOne3mind thanks for the feedback. I've opened an upstream issue with protagonist about this, so let's see what they come back with.

**Comment by theOne3mind** [comment] 2015-01-27 06:23
@danielgtaylor you're very welcome! thanks for the support and the awesome product!

**Comment by 3mind-** [comment] 2015-03-09 15:02
Protagonist 0.17.2 solved the issue for me.

**Comment by danielgtaylor** [comment] 2015-03-10 15:28
@3mind- thanks for confirming the fix. It looks like Protagonist is being updated this week to support iojs/node 0.12 so I'm going to wait for that, then bump dependencies and do another release.

**Comment by 3mind-** [comment] 2015-03-17 08:32
@danielgtaylor I think I have to revert my statement. Although it generates the output file kind of stable locally for me, on the buildserver (Jenkins in this case) it doesn't generate the documentation at all.

Let's hope the new version removes this issue once and for all.

**Comment by danielgtaylor** [comment] 2015-03-17 15:00
@3mind- do you still get the problem on the build server if you use `npm install -g aglio@experimental` instead? That will use Protagonist 0.18.7 as of this writing, which may contain some extra fixes.

**Comment by 3mind-** [comment] 2015-03-24 08:39
@danielgtaylor the experimental branch fixed the problem on the build-server.

Out of the last 11 builds, 11 successful documentation generations :+1: :100:

**Comment by tmenier** [comment] 2015-04-09 23:46
@danielgtaylor I wish I could say I was having the same luck. I'm on `aglio@experimental` on Windows 8.1 and experiencing all the same pains described herein. Just curious - is your build server running Windows? And is it using Protagonist 0.16.0 or is aglio@experimental with no tweaks/downgrades all it took?

**Comment by danielgtaylor** [comment] 2015-07-17 08:39
I believe this should all be fixed now with the latest few Aglio and Protagonist releases. Let me know if it isn't, and feel free to re-open!

**Closed by danielgtaylor** 2015-07-17 08:39 UTC
Labels: bug, upstream
