### ISSUE TITLE
Data Structures in response aren't fully generated

### ISSUE THREAD

**Issue by elizabeth-young** [danielgtaylor/aglio#188] opened 2015-11-02 09:56 UTC
Hi, 

Thanks for this library I have found it really useful.

After updating to version 2.2.0 I've found that my data structures are not being fully generated for responses, the updated examples also have this issue.

Previous example:
![previous response object using data structures](https://cloud.githubusercontent.com/assets/1730472/10878756/bc8e64be-8147-11e5-90dd-a4e2fdf71dec.PNG)

Version 2.2.0 example:
![version 2 2 0 response object using data structures](https://cloud.githubusercontent.com/assets/1730472/10878768/c7912a40-8147-11e5-8f4d-fee6d63f931d.PNG)

Thanks.

**Comment by kpashka** [comment] 2015-11-03 16:56
Experiencing same issue.

**Comment by hwestbrook** [comment] 2015-11-04 01:25
same issue

**Comment by danielgtaylor** [comment] 2015-11-04 18:26
@elizabeth-young @kpashka @hwestbrook thanks for reporting the issue. This is a regression in the new version of one of our dependencies, called Protagonist, which is itself a Node.js binding for Drafter. The main reason for moving to the new Protagonist is to support new upcoming features and support Node.js 4.x and 5.x. Currently, there are [several regressions being fixed](https://github.com/apiaryio/drafter/issues?utf8=%E2%9C%93&q=is%3Aissue+regression+) over in the Drafter repository.

Once those get fixed, a new version of Drafter will be released, then a new version of Protagonist and then when you install Aglio it will pick up the fixes. I will also do a patch release requiring the fixed version as the minimum allowed version.

Sorry about these issues, but I was feeling a lot of pain lacking support for Node.js 4.x and 5.x along with some parser bugs which have gotten fixed in the new version. At this point you have two options:

* Downgrade Aglio (`npm install aglio@2.1.1`) and get the old behavior back, but then you can only use Node.js 0.10 or 0.12
* Keep the current behavior and wait for the regression fixes, which are in progress right now.

Another issue related to the above is the lack of JSON Schema being generated with the new Protagonist. This is because the library used for that in the past was generating incorrect schemas, so it has been disabled until it can be fixed. An incorrect schema is worse than no schema, and work will be started shortly to get JSON Schema support working in Drafter itself. Again I apologize for the inconvenience, and I've had to make some difficult and inconvenient choices with what to support during this transitional period moving to the new Drafter/Protagonist.

Please feel free to chime in on the [Drafter issues](https://github.com/apiaryio/drafter/issues?q=is%3Aissue+is%3Aopen) or open new bugs on that repository to address any other MSON and related parser issues that you find.

**Comment by danielgtaylor** [comment] 2015-11-05 02:18
Just a quick update on the JSON Schema support: I have quickly written a simple [JSON Schema generator](https://github.com/danielgtaylor/aglio/blob/olio-theme/src/schema.coffee) and released it in the 1.4.0 version of the default Olio theme engine. If you reinstall Aglio you will get it, and it will generate schemas from MSON. It works with the example that I ship with Aglio ([example output](https://htmlpreview.github.io/?https://raw.githubusercontent.com/danielgtaylor/aglio/blob/master/examples/streak-triple.html#notes-note-list-get)), but consider it beta quality as it doesn't support all MSON features. The link above explains what it does support.

This does *not* help with the JSON body generation, which is handled within Drafter. Those bugs are in the process of being fixed, as explained above. Unfortunately there is no quick fix for them.

**Comment by hwestbrook** [comment] 2015-11-05 16:00
Thanks @danielgtaylor. I plan to downgrade aglio and node until this is resolved.

**Comment by elizabeth-young** [comment] 2015-11-06 10:57
Thanks for the update @danielgtaylor

**Comment by danielgtaylor** [comment] 2015-11-11 02:29
@hwestbrook @elizabeth-young please have another look, I've implemented a JSON example generator in Aglio that *should* support most features that the older Drafter did. Here is the [example blueprint](https://htmlpreview.github.io/?https://raw.githubusercontent.com/danielgtaylor/aglio/blob/master/examples/streak-triple.html#notes-note-list-get) showing both a working JSON body and JSON Schema. Let me know if you have any issues!

You'll need to reinstall Aglio to get the Olio theme 1.5.0.

**Comment by danielgtaylor** [comment] 2015-11-11 20:55
Closing as this should be fixed. Please reopen if you feel like I've missed something important!

**Closed by danielgtaylor** 2015-11-11 20:55 UTC
Labels: bug, upstream
