### ISSUE TITLE
iojs and node v0.12.0 support

### ISSUE THREAD

**Issue by garrows** [danielgtaylor/aglio#86] opened 2015-03-10 13:37 UTC
Hi, 
I'm using io.js `v1.4.3` and I had an error on install.

Also happens with node `v0.12.0`

Node `v0.10.36` works fine though.

```
npm install -g aglio

> fsevents@0.3.5 install /usr/local/lib/node_modules/aglio/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished

> protagonist@0.17.2 install /usr/local/lib/node_modules/aglio/node_modules/protagonist
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/CBlueprint.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/CBlueprintSourcemap.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/CSourceAnnotation.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/HTTP.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Section.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Serialize.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/SerializeJSON.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/SerializeYAML.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/Signature.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/snowcrash.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/csnowcrash.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/UriTemplateParser.o
  CXX(target) Release/obj.target/libsnowcrash/snowcrash/src/posix/RegexMatch.o
  LIBTOOL-STATIC Release/snowcrash.a
  CXX(target) Release/obj.target/libmarkdownparser/snowcrash/ext/markdown-parser/src/ByteBuffer.o
  CXX(target) Release/obj.target/libmarkdownparser/snowcrash/ext/markdown-parser/src/MarkdownNode.o
  CXX(target) Release/obj.target/libmarkdownparser/snowcrash/ext/markdown-parser/src/MarkdownParser.o
  LIBTOOL-STATIC Release/markdownparser.a
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/autolink.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/buffer.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/markdown.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/src_map.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/src/stack.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/houdini_href_e.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/houdini_html_e.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/html.o
  CC(target) Release/obj.target/libsundown/snowcrash/ext/markdown-parser/ext/sundown/html/html_smartypants.o
  LIBTOOL-STATIC Release/sundown.a
  CXX(target) Release/obj.target/protagonist/src/annotation.o
In file included from ../src/annotation.cc:1:
../src/protagonist.h:13:36: error: expected class name
    class Blueprint : public node::ObjectWrap {
                                   ^
../src/protagonist.h:28:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/glen/.node-gyp/1.4.3/deps/v8/include/v8.h:133:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/annotation.cc:1:
../src/protagonist.h:35:36: error: expected class name
    class Sourcemap : public node::ObjectWrap {
                                   ^
../src/protagonist.h:50:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/glen/.node-gyp/1.4.3/deps/v8/include/v8.h:133:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/annotation.cc:1:
../src/protagonist.h:57:43: error: expected class name
    class SourceAnnotation : public node::ObjectWrap {
                                          ^
../src/protagonist.h:69:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/glen/.node-gyp/1.4.3/deps/v8/include/v8.h:133:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/annotation.cc:1:
../src/protagonist.h:76:33: error: expected class name
    class Result : public node::ObjectWrap {
                                ^
../src/protagonist.h:92:48: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/glen/.node-gyp/1.4.3/deps/v8/include/v8.h:133:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/annotation.cc:1:
../src/protagonist.h:99:46: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
    extern v8::Handle<v8::Value> Parse(const v8::Arguments& args);
                                             ^~~~~~~~~~~~~
                                             v8::internal::Arguments
/Users/glen/.node-gyp/1.4.3/deps/v8/include/v8.h:133:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/annotation.cc:19:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/glen/.node-gyp/1.4.3/deps/v8/include/v8.h:878:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/annotation.cc:21:55: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'v8::Handle<v8::Value>
      (const v8::internal::Arguments &)'
    Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                      ^~~
/Users/glen/.node-gyp/1.4.3/deps/v8/include/v8.h:3824:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate,
               ^
../src/annotation.cc:23:29: error: no member named 'NewSymbol' in 'v8::String'
    t->SetClassName(String::NewSymbol("SourceAnnotation"));
                    ~~~~~~~~^
../src/annotation.cc:25:41: error: 'New' is a private member of 'v8::PersistentBase<v8::Function>'
    constructor = Persistent<Function>::New(t->GetFunction());
                                        ^
/Users/glen/.node-gyp/1.4.3/deps/v8/include/v8.h:637:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../src/annotation.cc:25:61: error: too few arguments to function call, expected 2, have 1
    constructor = Persistent<Function>::New(t->GetFunction());
                  ~~~~~~~~~~~~~~~~~~~~~~~~~                 ^
/Users/glen/.node-gyp/1.4.3/deps/v8/include/v8.h:637:3: note: 'New' declared here
  V8_INLINE static T* New(Isolate* isolate, T* that);
  ^
/Users/glen/.node-gyp/1.4.3/deps/v8/include/v8config.h:301:20: note: expanded from macro 'V8_INLINE'
# define V8_INLINE inline __attribute__((always_inline))
                   ^
../src/annotation.cc:26:26: error: no member named 'NewSymbol' in 'v8::String'
    exports->Set(String::NewSymbol("SourceAnnotation"), constructor);
                 ~~~~~~~~^
../src/annotation.cc:29:43: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> SourceAnnotation::New(const Arguments& args)
                                          ^~~~~~~~~
                                          v8::internal::Arguments
/Users/glen/.node-gyp/1.4.3/deps/v8/include/v8.h:133:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/annotation.cc:31:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/glen/.node-gyp/1.4.3/deps/v8/include/v8.h:878:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/annotation.cc:33:17: error: no member named 'Wrap' in 'protagonist::SourceAnnotation'
    annotation->Wrap(args.This());
    ~~~~~~~~~~  ^
../src/annotation.cc:33:26: error: member access into incomplete type 'const v8::internal::Arguments'
    annotation->Wrap(args.This());
                         ^
/Users/glen/.node-gyp/1.4.3/deps/v8/include/v8.h:133:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/protagonist/src/annotation.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/aglio/node_modules/protagonist
gyp ERR! node -v v1.4.3
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

> ws@0.5.0 install /usr/local/lib/node_modules/aglio/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> ws@0.4.31 install /usr/local/lib/node_modules/aglio/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "aglio"
npm ERR! node v1.4.3
npm ERR! npm  v2.6.1
npm ERR! code ELIFECYCLE

npm ERR! protagonist@0.17.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protagonist@0.17.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/glen/ga/npm-debug.log
```

**Comment by danielgtaylor** [comment] 2015-03-10 15:24
@garrows, this is a duplicate of #77. According to Apiary, the underlying library I need to support Aglio on iojs and node 0.12.x is being released this week:

https://github.com/danielgtaylor/aglio/issues/77#issuecomment-78005772

I believe they've switched to using [nan](https://www.npmjs.com/package/nan) so that in the future this is much less likely to happen again. It abstracts away many of the low-level differences between Node.js versions.

I'm going to close this in favor of the earlier ticket. Please add any new comments there!

**Closed by danielgtaylor** 2015-03-10 15:24 UTC
Labels: duplicate

**Comment by reselbob** [comment] 2015-03-10 21:46
I get the same error on MAC 10.10.2, Node v0.12.0... driving me nuts
