### ISSUE TITLE
Content header information is split arbitrarily. See example 

### ISSUE THREAD

**Issue by leokmob** [danielgtaylor/aglio#173] opened 2015-09-24 18:38 UTC
What I see is that a lot of cases where 1 or two chars at the end of a line are split into a separate paragraph.

This is the apib: 

```apib
FORMAT: 1A
HOST: http://www.google.com

# Centros Health API v2.0

## Introduction
This document describes API methods exposed on Centros Health API Server. The document is organized based on API root object such as user, patient, etc.  
```

*** This is HTML:

```html
</style></head><body><div class="container"><div><header><div class="page-header"><h1 id="top">Centros Health API v2.0</h1></div></header><div class="description"><p>0</p>
<h2 id="header-introducti-1">Introducti <a class="permalink" href="#header-introducti-1" aria-hidden="true">¶</a></h2>
<p>on
This document describes API methods exposed on Centros Health API Server. The document is organized based on API root object such as user, patient, etc.</p>
<style>
```

Note how Introduction is split into Introducti and on.

**Comment by jmdacruz** [comment] 2015-09-24 23:37
Suggestion: You should probably provide the exact aglio command line you are using to generate this (including the output of `aglio --version`) and also uploading the original apib file (not just pasting the content on the description, since there might be encoding problems that are hidden to the naked eye)

**Comment by leokmob** [comment] 2015-09-25 05:40
Here is the command:
~/node_modules/aglio/bin/aglio.js -i ~/LocalDev/GIT/MPM/MPM_HealthBook_Server_Workspace/MPM_HealthBook_Server/healthbook-apiary-api-1.md -o ~/Dropbox/CentrosHealth/v2.0/Docs/RawMaterials/healthbook-apiary-api-1-def.html --verbose

Verson: 
aglio leo$ ~/node_modules/aglio/bin/aglio.js --version
aglio 2.1.1
olio 1.2.1

**Comment by danielgtaylor** [comment] 2015-09-25 14:02
This looks like a duplicate of #127. Still not sure what is causing it or how to fix it unfortunately. Some people have had the issue go away just by doing a clean install or using a different computer. I wish I knew what was causing it. Closing this as a dupe, please continue the discussion at the linked issue.

**Closed by danielgtaylor** 2015-09-25 14:02 UTC
Labels: duplicate
